# Generated by Django 3.1.6 on 2021-02-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
                ('light_status', models.BooleanField(default=False)),
                ('brightness', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thermostat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
                ('actual_temperature', models.SmallIntegerField()),
                ('temperature_set', models.SmallIntegerField()),
            ],
        ),
    ]
