# Generated by Django 3.1.6 on 2021-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_light_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
