# Generated by Django 3.1.6 on 2021-02-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_auto_20210219_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
