# Generated by Django 3.1.6 on 2021-02-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20210210_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lights', to='restapi.room'),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermostats', to='restapi.room'),
        ),
    ]
