# Generated by Django 3.1.6 on 2021-02-15 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20210210_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='brightness',
            field=models.PositiveSmallIntegerField(blank=True, default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='actual_temperature',
            field=models.SmallIntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='temperature_set',
            field=models.SmallIntegerField(blank=True, default=10),
        ),
    ]
