# Generated by Django 3.1.6 on 2021-02-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20210216_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='name',
            field=models.CharField(default='Light', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
