# Generated by Django 3.1.6 on 2021-02-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_auto_20210217_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
