# Generated by Django 3.1.6 on 2021-02-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_auto_20210217_1049'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='light',
            unique_together={('room', 'name')},
        ),
    ]
