# Generated by Django 3.1.6 on 2021-02-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_auto_20210219_1202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='light',
            unique_together=set(),
        ),
    ]
