# Generated by Django 3.2.3 on 2021-05-19 18:40

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0017_auto_20210222_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='light',
            name='isRgb',
            field=models.BooleanField(default=False),
        ),
    ]
