# Generated by Django 3.2.3 on 2021-05-19 18:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0018_auto_20210519_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
